### ISSUE TITLE
500 Internal Server Error when generating PDF for example program

### ISSUE THREAD

**Issue by interlakedev** [phartenfeller/sveltekit-1.0-sqlite-demo-app#4]
Example link: https://sveltekit-demo.hartenfeller.dev/api/album/4/pdf/let-there-be-rock.pdf

**Comment by phartenfeller** [comment]
Thanks for reporting the issue!

The problem was that the font files were not included in the build.

<img width="482" alt="CleanShot 2023-08-12 at 18 14 01@2x" src="https://github.com/phartenfeller/sveltekit-1.0-sqlite-demo-app/assets/34486873/69fdf7dc-3f51-4d77-ac0d-140c978fdbbf">

I fixed this by explicitly providing these assets to the container.

**Comment by interlakedev** [comment]
Thank you for the quick response!
